### ISSUE TITLE
Adding Roles to the Discord server

### ISSUE THREAD

**Issue by Djacon** [codewars/discord-bot#61]
At the moment there is no variety of roles on the codewars server as such. Now on the server there are roles only for administration. I would like to add roles for all users, as it is done on the site.

#### A possible list of what we would need to do:
- [ ] Create new roles on the server (8kyu -> 2dan, and higher if necessary)
- [ ] Implement command /verify to verify the user on the server
- [ ] Implement command /roleup to promote the role

#### Task description:
1. Create roles with colors corresponding to their ranks
2. It is assumed that in order to get a role on the server, the user will have to write the command `/verify key: "your key"` to the bot in private messages.
3. It is also assumed that in the case of increasing the rank of the user, the user will have to write to the bot in private messages with the command `/roleup`.

### Problems and possible solutions:

In the case of the `/verify` command, it would be necessary to provide the bot with a key identifying the user. I think we need to create an individual key generator in the user's account settings on the site.

In the future, in case the user's rank is increased, we need to check this event in some way. I think that in order for the bot not to check in real time the change of rank, we should simply add a command `/roleup`, which, using the previously obtained key, make a check of the user's account for its promotion.

**Comment by kazk** [comment]
I'm not a fan of the idea of the rank roles.

For linking accounts, we can use OAuth.

- On Codewars, add "Link your Discord Account" button like the GitHub one. This will store the Discord user id in the user's record.
- Add `/codewars-account`
  - `/codewars-account link` that sends your Discord id to Codewars to find your account. The bot will store this association somewhere.
  - `/codewars-account unlink` to remove yourself from the bot's database
  - `/codewars-account find user:@user` to get the Discord user's Codewars id/profile

We can add :heavy_check_mark: role to verified users.
